Support latest django
lambdalisue/django-roughpages pull request #4
Opened 2016-10-01 06:25 UTC by giginet

This PR adds supported versions

- Python3.5
- Django1.8~1.10

2016-10-01 06:26 UTC, giginet commented
@lambdalisue Please review it

2016-10-01 07:47 UTC, lambdalisue requested changes
Please drop Python 2.6/3.2 and Django 1.2-1.6 as well.

2016-10-01 07:47 UTC, lambdalisue commented on tox.ini
> +    py35-django{18,19,110}
OK. Now we are living in 2016, let's drop the followings. Please modify `README.md` as well.

- Django 1.2 ~ 1.6
- Python 2.6
- Python 3.2

https://docs.djangoproject.com/en/1.10/faq/install/#what-python-version-can-i-use-with-django

2016-10-01 07:47 UTC, lambdalisue commented on src/roughpages/tests/test_views.py
> +        if django.VERSION >= (1, 9):
Probably from 1.8
https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/#django-template-loader

2016-10-01 07:47 UTC, lambdalisue commented on src/roughpages/views.py
> +    if django.VERSION >= (1, 9):
From 1.8

2016-10-01 07:47 UTC, lambdalisue commented on .travis.yml
> +  - 3.5
Drop 2.6

2016-10-01 07:47 UTC, lambdalisue commented on README.rst
> +    Django 1.2 - 1.10
Drop Python 2.6 and Django 1.2-1.6

2016-10-01 07:47 UTC, lambdalisue commented on setup.py
>          'Programming Language :: Python :: 2.6',
Drop 2.6

2016-10-01 07:47 UTC, lambdalisue commented on tox.ini
> +    py35-django{18,19,110}
Drop Python 2.6 and Django 1.2-1.6

2016-10-01 07:47 UTC, lambdalisue commented on tox.ini
> +    django{12,13}: pip install --upgrade "django-appconf==1.0.1"
Drop this line.

2016-10-01 07:47 UTC, lambdalisue commented on tox.ini
> +    py{26,27}: coverage run --source=src/roughpages runtests.py []
Drop 26

2016-10-02 08:41 UTC, lambdalisue approved these changes
LGTM

2016-10-02 08:41 UTC, merged

2016-10-02 08:42 UTC, giginet commented
Thank you.
 distribute it please.